"""The paper's eight figures.

Every figure is generated by a function here and by nothing else. When a number
changes, one command regenerates all of them; no figure is ever produced by hand
in a spreadsheet. That discipline is what makes revising an evaluation in
October survivable.

F1  Campaign GPU timeline with idle regions shaded       motivation
F2  Reported utilisation vs achieved occupancy           contribution 3
F3  System architecture                                  design
F4  Workload signatures on the occupancy/bandwidth plane workload selection
F5  Measured slowdown heatmap, all pairings              the dataset
F6  Predicted vs actual slowdown + feature ablation      the model
F7  Throughput against slowdown-bound violations         headline result
F8  Achieved occupancy by policy                         why throughput moved
"""
from __future__ import annotations

from pathlib import Path
from typing import List, Optional

import matplotlib.patches as mpatches
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

from ..workloads import registry
from . import style

OUT_DIR = Path("figures")


def _save(fig, name: str, out_dir: Path = OUT_DIR) -> Path:
    out_dir.mkdir(parents=True, exist_ok=True)
    # reserve a strip at the bottom so the provenance footer cannot collide with
    # an axis label; tight_layout alone does not know the footer exists
    try:
        fig.tight_layout(rect=(0, 0.055, 1, 1))
    except Exception:  # noqa: BLE001
        pass
    path = out_dir / f"{name}.png"
    fig.savefig(path)
    fig.savefig(out_dir / f"{name}.pdf")
    plt.close(fig)
    return path


# ---------------------------------------------------------------------------
# F1 -- the motivating picture
# ---------------------------------------------------------------------------
def f1_campaign_timeline(trace, kind: str, out_dir: Path = OUT_DIR,
                         max_pipelines: int = 8) -> Path:
    """GPU occupancy over a campaign, with held-but-idle regions shaded.

    A Gantt-style timeline because the data's job is to show WHEN the device was
    held versus when it was used; a bar chart of totals would hide exactly the
    structure that motivates the project.
    """
    style.apply()
    df = trace.stages.copy()
    df = df[df["pipeline_id"] < max_pipelines]
    fig, ax = plt.subplots(figsize=style.TWO_COL_TALL)

    occ_of = {w: registry.get(w).sim_occupancy for w in df["workload"].unique()}
    cmap = plt.get_cmap(style.SEQUENTIAL)

    for pid, grp in df.groupby("pipeline_id"):
        grp = grp.sort_values("stage_idx")
        start = pd.to_numeric(grp["start_s"], errors="coerce").min()
        end = pd.to_numeric(grp["end_s"], errors="coerce").max()
        if np.isnan(start) or np.isnan(end):
            continue
        ax.add_patch(mpatches.Rectangle(
            (start, pid - 0.42), end - start, 0.84, facecolor="#f0f0f0",
            edgecolor="#cfcfcf", linewidth=0.5, zorder=1))
        for _, r in grp.iterrows():
            s, e = r["start_s"], r["end_s"]
            occ = occ_of.get(r["workload"], 0.0)
            if pd.isna(s) or pd.isna(e) or not r["gpu"] or occ <= 0:
                continue
            ax.add_patch(mpatches.Rectangle(
                (s, pid - 0.42), e - s, 0.84, facecolor=cmap(0.25 + 0.7 * occ),
                edgecolor="white", linewidth=0.4, zorder=2))

    n_rows = min(max_pipelines, df["pipeline_id"].nunique())
    ax.set_xlim(0, float(pd.to_numeric(df["end_s"], errors="coerce").max()) * 1.02)
    ax.set_ylim(-0.7, n_rows - 0.3)
    ax.set_xlabel("campaign time (s)")
    ax.set_ylabel("pipeline instance")
    ax.set_yticks(range(n_rows))
    ax.grid(axis="y", visible=False)

    idle = trace.held_but_idle_fraction * 100
    under = trace.held_but_under_occupied_fraction * 100
    ax.set_title(f"GPU held for the whole pipeline, used by part of it\n"
                 f"held but idle {idle:.1f}%   ·   held but under-occupied {under:.1f}%",
                 loc="left", color=style.INK)
    ax.legend(handles=[
        mpatches.Patch(facecolor="#f0f0f0", edgecolor="#cfcfcf", label="device held"),
        mpatches.Patch(facecolor=cmap(0.35), label="GPU work, low occupancy"),
        mpatches.Patch(facecolor=cmap(0.85), label="GPU work, high occupancy"),
    ], loc="upper right", ncol=3, fontsize=6)
    style.footer(fig, kind, f"policy={trace.policy}")
    return _save(fig, "f1_campaign_timeline", out_dir)


# ---------------------------------------------------------------------------
# F2 -- utilisation overstates occupancy
# ---------------------------------------------------------------------------
def f2_utilisation_vs_occupancy(signatures: pd.DataFrame, kind: str,
                                out_dir: Path = OUT_DIR) -> Path:
    """Paired bars: what nvidia-smi reports against what the device achieved.

    Two measures of the same quantity on one axis, so a paired bar is right and
    a dual axis would be wrong.
    """
    style.apply()
    df = signatures[["workload", "util_gpu_mean", "sm_occupancy_mean"]].dropna()
    df = df.sort_values("sm_occupancy_mean")

    y = np.arange(len(df))
    h = 0.38
    fig, ax = plt.subplots(figsize=(style.TWO_COL[0], 0.3 * len(df) + 1.4))
    ax.barh(y + h / 2 + 0.01, df["util_gpu_mean"], height=h,
            color=style.PALETTE[3], label="reported utilisation")
    ax.barh(y - h / 2 - 0.01, df["sm_occupancy_mean"], height=h,
            color=style.PALETTE[0], label="achieved occupancy")

    for i, (_, r) in enumerate(df.iterrows()):
        if r["sm_occupancy_mean"] > 0:
            ratio = r["util_gpu_mean"] / r["sm_occupancy_mean"]
            ax.text(max(r["util_gpu_mean"], r["sm_occupancy_mean"]) + 0.015, i,
                    f"{ratio:.1f}x", va="center", fontsize=6, color=style.MUTED)

    ax.set_yticks(y)
    ax.set_yticklabels(df["workload"], fontsize=6.5)
    ax.set_xlabel("fraction of peak")
    ax.set_xlim(0, 1.22)
    ax.grid(axis="y", visible=False)
    # The legend sits above the axes: every bar reaches toward x=1.0 and the
    # overstatement labels occupy the right margin, so there is no free corner
    # inside the plot area.
    ax.legend(loc="lower center", bbox_to_anchor=(0.5, 1.005), ncol=2, fontsize=6.5)
    ratios = (df["util_gpu_mean"] / df["sm_occupancy_mean"].replace(0, np.nan)).dropna()
    ax.set_title("Reported utilisation overstates achieved occupancy\n"
                 f"median overstatement {ratios.median():.1f}x, worst {ratios.max():.1f}x",
                 loc="left", color=style.INK, pad=22)
    style.footer(fig, kind)
    return _save(fig, "f2_utilisation_vs_occupancy", out_dir)


# ---------------------------------------------------------------------------
# F3 -- architecture
# ---------------------------------------------------------------------------
def f3_architecture(out_dir: Path = OUT_DIR) -> Path:
    """Module diagram. A schematic, so no provenance question arises."""
    style.apply()
    fig, ax = plt.subplots(figsize=(style.TWO_COL[0], 3.6))
    ax.set_axis_off()
    ax.set_xlim(0, 10)
    ax.set_ylim(0, 10)

    def box(x, y, w, h, title, sub, fc="#ffffff"):
        ax.add_patch(mpatches.FancyBboxPatch(
            (x, y), w, h, boxstyle="round,pad=0.06,rounding_size=0.12",
            facecolor=fc, edgecolor=style.INK, linewidth=0.8))
        ax.text(x + w / 2, y + h * 0.62, title, ha="center", va="center",
                fontsize=7.5, fontweight="bold", color=style.INK)
        ax.text(x + w / 2, y + h * 0.26, sub, ha="center", va="center",
                fontsize=6, color=style.MUTED)

    def arrow(x1, y1, x2, y2):
        ax.annotate("", xy=(x2, y2), xytext=(x1, y1),
                    arrowprops=dict(arrowstyle="-|>", color=style.MUTED,
                                    linewidth=0.8, shrinkA=2, shrinkB=2))

    box(0.3, 8.2, 9.4, 1.2, "M6  Evaluation harness and trace-driven simulator",
        "campaign-scale replay, validated against hardware", fc="#f7f7f7")
    box(0.3, 5.6, 2.9, 1.9, "M1  Pipeline executor",
        "four-stage DAG\nN concurrent instances")
    box(3.6, 5.6, 2.8, 1.9, "M5  Stage-aware scheduler",
        "greedy under bound\nILP gap, bandit")
    box(6.8, 5.6, 2.9, 1.9, "M4  Slowdown predictor",
        "GBM, leave-one-out\nprecomputed table")
    box(6.8, 3.0, 2.9, 1.7, "M3  Pair dataset",
        "78 pairings under MPS\nOOM as an outcome")
    box(3.6, 3.0, 2.8, 1.7, "MPS control plane",
        "daemon, thread %\n(mechanism, not policy)", fc="#f2f2f2")
    box(0.3, 3.0, 2.9, 1.7, "M2  Counter profiler",
        "DCGM 100 ms\n18-feature signature")
    box(2.2, 0.8, 5.6, 1.3, "2 x NVIDIA T4 on one node", "16 GB each", fc="#ececec")

    for a in [(1.75, 5.6, 1.75, 4.7), (5.0, 5.6, 5.0, 4.7), (8.25, 5.6, 8.25, 4.7),
              (6.8, 6.55, 6.4, 6.55), (3.6, 6.55, 3.2, 6.55),
              (8.25, 3.0, 8.25, 2.1), (5.0, 3.0, 5.0, 2.1), (1.75, 3.0, 1.75, 2.1),
              (5.0, 8.2, 5.0, 7.5)]:
        arrow(*a)

    ax.set_title("Stage-aware GPU co-location: module architecture",
                 loc="left", color=style.INK, fontsize=9)
    return _save(fig, "f3_architecture", out_dir)


# ---------------------------------------------------------------------------
# F4 -- workload spread
# ---------------------------------------------------------------------------
def f4_roofline_plane(signatures: pd.DataFrame, kind: str,
                      out_dir: Path = OUT_DIR) -> Path:
    """Where each workload sits on the occupancy / bandwidth plane.

    Evidence that the zoo was selected deliberately rather than conveniently,
    which reviewers reward.
    """
    style.apply()
    fig, ax = plt.subplots(figsize=style.ONE_COL_TALL)

    fams = sorted({registry.get(w).family for w in signatures["workload"]
                   if w in registry.ALL})
    fam_color = {f: style.PALETTE[i % len(style.PALETTE)] for i, f in enumerate(fams)}

    for _, r in signatures.iterrows():
        w = r["workload"]
        if w not in registry.ALL:
            continue
        spec = registry.get(w)
        x = r.get("sm_occupancy_mean", spec.sim_occupancy)
        y = r.get("dram_active_mean", spec.sim_dram_bw)
        size = 14 + 26 * (spec.sim_vram_mb / 12000.0)
        ax.scatter(x, y, s=size, color=fam_color[spec.family],
                   edgecolor="white", linewidth=0.6, zorder=3)
        ax.annotate(w.replace("_infer", "").replace("_", " ")[:14], (x, y),
                    textcoords="offset points", xytext=(4, 3),
                    fontsize=5.2, color=style.MUTED)

    ax.set_xlabel("achieved occupancy")
    ax.set_ylabel("DRAM activity")
    ax.set_xlim(0, 0.9)
    ax.set_ylim(0, 0.8)
    ax.legend(handles=[plt.Line2D([], [], marker="o", linestyle="", color=c,
                                  markersize=4, label=f)
                       for f, c in fam_color.items()],
              loc="upper left", fontsize=5.5, ncol=2)
    ax.set_title("Workload zoo spans the plane\n(marker size = VRAM footprint)",
                 loc="left", color=style.INK)
    style.footer(fig, kind)
    return _save(fig, "f4_roofline_plane", out_dir)


# ---------------------------------------------------------------------------
# F5 -- slowdown heatmap
# ---------------------------------------------------------------------------
def f5_slowdown_heatmap(pairs: pd.DataFrame, kind: str, out_dir: Path = OUT_DIR,
                        thread_pct: int = 100) -> Path:
    """Every pairing's measured slowdown. Sequential ramp, single hue."""
    style.apply()
    df = pairs[pairs["thread_pct_a"] == thread_pct].copy()
    names = sorted(set(df["workload_a"]) | set(df["workload_b"]))
    idx = {n: i for i, n in enumerate(names)}
    M = np.full((len(names), len(names)), np.nan)
    OOM = np.zeros_like(M, dtype=bool)

    for (a, b), grp in df.groupby(["workload_a", "workload_b"]):
        i, j = idx[a], idx[b]
        if grp["oom"].astype(bool).all():
            OOM[i, j] = True
            continue
        vals = pd.to_numeric(grp["slowdown_a"], errors="coerce").dropna()
        if not vals.empty:
            M[i, j] = vals.median()

    fig, ax = plt.subplots(figsize=(5.0, 4.4))
    vmax = np.nanpercentile(M, 99) if np.isfinite(M).any() else 2.0
    im = ax.imshow(M, cmap=style.SEQUENTIAL, vmin=1.0, vmax=max(vmax, 1.05),
                   aspect="auto")

    for i in range(len(names)):
        for j in range(len(names)):
            if OOM[i, j]:
                ax.add_patch(mpatches.Rectangle(
                    (j - 0.5, i - 0.5), 1, 1, facecolor="#3a3a3a",
                    edgecolor="white", linewidth=0.4))
                ax.text(j, i, "x", ha="center", va="center", fontsize=6, color="white")

    ax.set_xticks(range(len(names)))
    ax.set_yticks(range(len(names)))
    ax.set_xticklabels([n[:16] for n in names], rotation=60, ha="right", fontsize=5.5)
    ax.set_yticklabels([n[:16] for n in names], fontsize=5.5)
    ax.set_xlabel("co-tenant")
    ax.set_ylabel("target workload (the one being slowed)")
    ax.grid(visible=False)
    cb = fig.colorbar(im, ax=ax, fraction=0.042, pad=0.03)
    cb.set_label("slowdown (co-located / solo)", fontsize=7)
    cb.ax.tick_params(labelsize=6)
    ax.set_title(f"Measured pairwise slowdown at {thread_pct}% partition\n"
                 f"dark cells: VRAM exhaustion ({int(OOM.sum())} pairings)",
                 loc="left", color=style.INK)
    style.footer(fig, kind)
    return _save(fig, "f5_slowdown_heatmap", out_dir)


# ---------------------------------------------------------------------------
# F6 -- model quality
# ---------------------------------------------------------------------------
def f6_predicted_vs_actual(cv_predictions: pd.DataFrame,
                           a1_table: Optional[pd.DataFrame], kind: str,
                           out_dir: Path = OUT_DIR) -> Path:
    """Left: held-out predicted vs actual. Right: feature-set ablation."""
    style.apply()
    fig, axes = plt.subplots(1, 2, figsize=(style.TWO_COL[0], 2.8),
                             gridspec_kw={"width_ratios": [1.25, 1]})

    ax = axes[0]
    x = cv_predictions["y_true"].values
    y = cv_predictions["y_pred"].values
    lo, hi = float(min(x.min(), y.min())) - 0.02, float(max(x.max(), y.max())) + 0.02
    ax.plot([lo, hi], [lo, hi], color=style.MUTED, linewidth=0.8,
            linestyle="--", zorder=1)
    ax.scatter(x, y, s=7, color=style.PALETTE[0], alpha=0.45,
               edgecolor="none", zorder=2)
    ax.set_xlabel("measured slowdown")
    ax.set_ylabel("predicted slowdown")
    ax.set_xlim(lo, hi)
    ax.set_ylim(lo, hi)
    ax.set_title(f"Held-out workloads\nMAE {float(np.mean(np.abs(x - y))):.3f}",
                 loc="left", color=style.INK)

    ax2 = axes[1]
    if a1_table is not None and not a1_table.empty:
        t = a1_table.sort_values("mae")
        colors = [style.PALETTE[3] if f == "utilisation" else style.PALETTE[0]
                  for f in t["feature_set"]]
        ax2.barh(range(len(t)), t["mae"], color=colors, height=0.55)
        ax2.set_yticks(range(len(t)))
        ax2.set_yticklabels(t["feature_set"], fontsize=6.5)
        ax2.set_xlabel("leave-one-workload-out MAE")
        ax2.grid(axis="y", visible=False)
        for i, (_, r) in enumerate(t.iterrows()):
            ax2.text(r["mae"] * 1.02, i, f"{r['mae']:.3f}", va="center",
                     fontsize=6, color=style.MUTED)
        ax2.set_xlim(0, float(t["mae"].max()) * 1.32)
        ax2.set_title("Feature set (A1)", loc="left", color=style.INK)
    else:
        ax2.set_axis_off()

    fig.tight_layout()
    style.footer(fig, kind)
    return _save(fig, "f6_predicted_vs_actual", out_dir)


# ---------------------------------------------------------------------------
# F7 -- the headline
# ---------------------------------------------------------------------------
def f7_throughput_vs_violations(summary: pd.DataFrame, kind: str,
                                out_dir: Path = OUT_DIR) -> Path:
    """Throughput against bound violations. Up and to the left is better."""
    style.apply()
    fig, ax = plt.subplots(figsize=(4.2, 3.2))

    # The three predictive policies frequently land on exactly zero violations,
    # so without a dodge the last one drawn hides the others entirely. Offsets
    # are cosmetic and stated on the figure.
    dodge = {"utilisation": -0.55, "greedy": 0.0, "oracle": 0.55}
    marks = {"utilisation": "^", "greedy": "o", "oracle": "v"}
    dashes = {"utilisation": (3, 2), "greedy": (), "oracle": (1, 1.5)}
    overlapped = False

    for policy in ["exclusive", "blind", "utilisation", "greedy", "oracle"]:
        sub = summary[summary["policy"] == policy]
        if sub.empty:
            continue
        c = style.color_policy(policy)
        if policy in ("exclusive", "blind"):
            ax.scatter(sub["violation_rate"] * 100, sub["throughput_per_hour"],
                       color=c, s=46, marker="D" if policy == "blind" else "s",
                       edgecolor="white", linewidth=0.7, zorder=5,
                       label=style.label_policy(policy))
        else:
            sub2 = sub.sort_values("throughput_per_hour")
            if sub2["violation_rate"].nunique() == 1:
                overlapped = True
            line, = ax.plot(sub2["violation_rate"].values * 100 + dodge[policy],
                            sub2["throughput_per_hour"].values, color=c,
                            marker=marks[policy], markersize=4, linewidth=1.3,
                            markeredgecolor="white", markeredgewidth=0.5,
                            zorder=4 if policy == "greedy" else 3,
                            label=style.label_policy(policy))
            if dashes[policy]:
                line.set_dashes(dashes[policy])

    ax.set_xlabel("slowdown-bound violations (% of stages)")
    ax.set_ylabel("throughput (pipelines / hour)")
    ax.set_xlim(-3, max(72, float(summary["violation_rate"].max()) * 100 + 6))
    ax.legend(loc="center right", fontsize=6.2)
    ax.set_title("More work done, fewer promises broken"
                 + ("\npredictive policies dodged horizontally where they coincide"
                    if overlapped else ""),
                 loc="left", color=style.INK, fontsize=8.5)
    style.footer(fig, kind)
    return _save(fig, "f7_throughput_vs_violations", out_dir)


# ---------------------------------------------------------------------------
# F8 -- why throughput moved
# ---------------------------------------------------------------------------
def f8_occupancy_by_policy(summary: pd.DataFrame, kind: str,
                           out_dir: Path = OUT_DIR,
                           bound: Optional[float] = 1.25) -> Path:
    """Achieved occupancy per policy: the mechanism behind the throughput gain."""
    style.apply()
    rows = []
    for policy in ["exclusive", "blind", "utilisation", "greedy", "oracle"]:
        sub = summary[summary["policy"] == policy]
        if sub.empty:
            continue
        if policy in ("greedy", "utilisation", "oracle") and bound is not None:
            pick = sub[np.isclose(sub["slowdown_bound"], bound)]
            sub = pick if not pick.empty else sub
        rows.append({"policy": policy,
                     "occupancy": sub.iloc[0]["mean_achieved_occupancy"]})
    t = pd.DataFrame(rows)

    fig, ax = plt.subplots(figsize=style.ONE_COL)
    xs = np.arange(len(t))
    ax.bar(xs, t["occupancy"], color=[style.color_policy(p) for p in t["policy"]],
           width=0.6)
    for i, v in enumerate(t["occupancy"]):
        ax.text(i, v + 0.015, f"{v:.2f}", ha="center", fontsize=6.5, color=style.MUTED)
    ax.set_xticks(xs)
    ax.set_xticklabels([style.label_policy(p).split(" (")[0] for p in t["policy"]],
                       rotation=20, ha="right", fontsize=6.5)
    ax.set_ylabel("time-weighted achieved occupancy")
    ax.set_ylim(0, max(float(t["occupancy"].max()) * 1.25, 0.2))
    ax.grid(axis="x", visible=False)
    ax.set_title(f"Achieved occupancy (bound {bound})", loc="left", color=style.INK)
    style.footer(fig, kind)
    return _save(fig, "f8_occupancy_by_policy", out_dir)


def make_all(trace, signatures: pd.DataFrame, pairs: pd.DataFrame,
             cv_predictions: pd.DataFrame, a1_table: Optional[pd.DataFrame],
             summary: pd.DataFrame, kind: str, out_dir: Path = OUT_DIR,
             verbose: bool = True) -> List[Path]:
    """Regenerate every figure. One command, no manual steps."""
    made: List[Path] = []
    jobs = [
        ("F1", lambda: f1_campaign_timeline(trace, kind, out_dir)),
        ("F2", lambda: f2_utilisation_vs_occupancy(signatures, kind, out_dir)),
        ("F3", lambda: f3_architecture(out_dir)),
        ("F4", lambda: f4_roofline_plane(signatures, kind, out_dir)),
        ("F5", lambda: f5_slowdown_heatmap(pairs, kind, out_dir)),
        ("F6", lambda: f6_predicted_vs_actual(cv_predictions, a1_table, kind, out_dir)),
        ("F7", lambda: f7_throughput_vs_violations(summary, kind, out_dir)),
        ("F8", lambda: f8_occupancy_by_policy(summary, kind, out_dir)),
    ]
    for tag, fn in jobs:
        try:
            p = fn()
            made.append(p)
            if verbose:
                print(f"  {tag}  {p}")
        except Exception as exc:  # noqa: BLE001
            if verbose:
                print(f"  {tag}  FAILED: {type(exc).__name__}: {exc}")
    return made
